{{- /* Use the nodes helper template that defines everything for a single CDR Node */ -}}
{{- range $theCdrNodeName, $theCdrNodeCtx := include "smilecdr.cdrNodes" . | fromYaml -}}
  {{- $theCdrNodeSpec := $theCdrNodeCtx.Values -}}
    {{- if eq ((include "sscsi.enabled" $theCdrNodeCtx ) | trim ) "true" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sscsi.secretProviderClassName" $theCdrNodeCtx | lower }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: {{ default (.Values.image.credentials).provider "aws" }}
  parameters:
    objects: |
      {{ include "sscsi.objects" $theCdrNodeCtx | nindent 6 | trim }}
  secretObjects:
    {{- include "sscsi.secretObjects" $theCdrNodeCtx | nindent 2 }}
---
  {{- end -}}
{{ end }}
