{{- /*
This template and the two helper templates it uses are deprecated and will be removed at some point.
Passing in secret values directly via the chart is not recommended, so the functionality will be removed to prevent
bad habits forming.
*/ -}}
{{- range $v := (include "imagePullSecrets" . | fromYamlArray ) -}}
{{- if eq $v.type "values" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.name  }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "dockerconfigjson.encoded" $v }}
{{ end }}
---
{{ end }}
