{{- $cdrNodes := include "smilecdr.nodes" . | fromYaml  -}}
{{- range $theIngressName, $theIngressSpec := include "smilecdr.ingresses" . | fromYaml -}}
  {{- $ingressRules := (include "smilecdr.ingress.rules" (dict "ingressSpec" $theIngressSpec "cdrNodes" $cdrNodes) | fromYamlArray) -}}
  {{- if $ingressRules -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $.Release.Name $theIngressSpec.resourceSuffix }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "smilecdr.labels" $ | nindent 4 | trim }}
  annotations:
    {{- $theIngressSpec.annotations | toYaml | nindent 4 }}
spec:
  {{ with $theIngressSpec.ingressClassName -}}
  ingressClassName: {{ . }}
  {{ end -}}
  rules:
    {{- $ingressRules | toYaml | nindent 4 }}
---
  {{ end }}
{{ end }}
