{{- /* Use the nodes helper template that defines everything for a single CDR Node */ -}}
{{- range $theNodeName, $theNodeCtx := include "smilecdr.nodes" . | fromYaml -}}
  {{- $theNodeSpec := $theNodeCtx.Values -}}
    {{- if eq ((include "sscsi.enabled" $theNodeCtx ) | trim ) "true" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sscsi.secretProviderClassName" $theNodeCtx | lower }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: {{ default (.Values.image.credentials).provider "aws" }}
  parameters:
    objects: |
      {{ include "sscsi.objects" $theNodeCtx | nindent 6 | trim }}
  secretObjects:
    {{- include "sscsi.secretObjects" $theNodeCtx | nindent 2 }}
---
  {{- end -}}
{{ end }}
