{{- range $theNodeName, $theNodeCtx := include "smilecdr.nodes" . | fromYaml -}}
  {{- $theNodeSpec := $theNodeCtx.Values -}}
  {{- if $theNodeSpec.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ $theNodeSpec.resourceSuffix }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- toYaml $theNodeSpec.cdrNodeLabels | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Release.Name }}-{{ $theNodeSpec.resourceSuffix }}
  minReplicas: {{ default 1 $theNodeSpec.autoscaling.minReplicas }}
  maxReplicas: {{ default 4 $theNodeSpec.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ default 80 $theNodeSpec.autoscaling.targetCPUUtilizationPercentage }}
---
{{ end }}
{{- end -}}
