{{- range $theNodeName, $theNodeSpec := include "smilecdr.nodes" . | fromYaml -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{ $theNodeSpec.resourceSuffix }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- toYaml $theNodeSpec.cdrNodeLabels | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- toYaml $theNodeSpec.cdrNodeSelectorLabels | nindent 6 }}
---
{{ end }}
