apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-scdr
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "smilecdr.labels" . | nindent 4 | trim }}
  annotations:
    {{ include "ingress.annotations" . | nindent 4 | trim }}
spec:
  rules:
    {{- include "ingress.hosts" . | nindent 4 }}
