apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scdr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "smilecdr.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smilecdr.labels" . | nindent 8 }}
    spec:
      {{- with (include "dockerconfigjson.secretName" .) }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "smilecdr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "smilecdr.initContainers" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            {{- include "smilecdr.readinessProbe" . | nindent 12 }}
          startupProbe:
            exec:
              command:
              - /usr/bin/sh
              - -c
              - "/usr/bin/grep \"Smile, we're up and running! :)\" /home/smile/smilecdr/log/smile.log"
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "smilecdr.dbEnvVars" . | nindent 12 }}
            {{- with include "smilecdr.jvmargs" . }}
            - name: JVMARGS
              value: {{ . }}
            {{- end }}
          ports:
            {{- range $k, $v := include "smilecdr.services" . | fromYaml }}
            - name: {{ $v.svcName }}
              containerPort: {{ $v.port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            {{ include "smilecdr.volumeMounts" . | nindent 12 | trim }}
      volumes:
        {{ include "smilecdr.volumes" . | nindent 8 | trim }}
      restartPolicy: Always
