{{- range $theComponentName, $theComponentSpec := include "pmp.components" . | fromYaml -}}
  {{- if $theComponentSpec.sscsi.enabled -}}
  {{- if eq $theComponentSpec.componentName "memberPortalll" -}}
    {{- fail (printf "\n$theComponentSpec\n\n%s" (toYaml $theComponentSpec)) -}}
  {{- end }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $theComponentSpec.sscsi.secretProviderClassName | lower }}
  labels:
    {{- toYaml $theComponentSpec.componentLabels | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider: "aws"
  parameters:
    objects: |
      {{ toYaml $theComponentSpec.sscsi.objects | nindent 6 | trim }}
  secretObjects:
  {{ toYaml $theComponentSpec.sscsi.syncedSecrets | nindent 2 | trim }}
---
{{ end -}}
{{- end -}}
