{{- range $theComponentName, $theComponentSpec := include "pmp.components" . | fromYaml -}}
  {{- if $theComponentSpec.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $theComponentSpec.serviceAccountName }}
  labels:
    {{- toYaml $theComponentSpec.componentLabels | nindent 4 }}
  {{- with $theComponentSpec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
  {{- end }}
{{ end }}
