{{- range $k, $v := .Values.components -}}
{{- $componentContext := (include "component.getMergedContext" (dict "componentName" $k "componentObject" $v "globalObject" $) | fromYaml) -}}
{{- if and $v.enabled  $v.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "component.serviceAccountName" $componentContext }}
  labels:
    {{- include "component.labels" $componentContext | nindent 4 }}
  {{- with $v.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{ end }}
