{{- range $k, $v := .Values.components -}}
{{- $componentContext := (include "component.getMergedContext" (dict "componentName" $k "componentObject" $v "globalObject" $) | fromYaml) -}}
{{- if $v.enabled -}}

{{- if eq ((include "sdhCommon.sscsi.enabled" $componentContext ) | trim ) "true" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sdhCommon.sscsi.secretProviderClassName" $componentContext | lower }}
  labels:
    {{- include "component.labels" $componentContext | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider: "aws"
  parameters:
    objects: |
      {{ include "sdhCommon.sscsi.objects" $componentContext | nindent 6 | trim }}
  secretObjects:
  {{ include "sdhCommon.sscsi.syncedSecrets" $componentContext | nindent 2 | trim }}
---
{{- end -}}
{{- end -}}
{{- end -}}
