{{- range $k, $v := .Values.components -}}
  {{- if $v.enabled -}}
    {{- $componentContext := (include "component.getMergedContext" (dict "componentName" $k "componentObject" $v "globalObject" $) | fromYaml) -}}
    {{- range $secret := (include "sdhCommon.secrets.k8sSecretObjects" $componentContext | fromYamlArray) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    {{- include "component.labels" $componentContext | nindent 4 }}
type: Opaque
data: {{- $secret.data | toYaml | nindent 2 }}
---
    {{- end }}
  {{ end }}
{{ end }}
