{{- range $theComponentName, $theComponentSpec := include "pmp.components" . | fromYaml -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $theComponentSpec.fullName }}
  labels:
    {{- toYaml $theComponentSpec.componentLabels | nindent 4 }}
spec:
  type: {{ $theComponentSpec.service.type }}
  ports:
    - port: {{ $theComponentSpec.service.port }}
      targetPort: {{ $theComponentSpec.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml $theComponentSpec.componentSelectorLabels | nindent 4 }}
---
{{ end }}
