{{- range $theComponentName, $theComponentSpec := include "pmp.components" . | fromYaml -}}

  {{- range $secret := $theComponentSpec.k8sSecretObjects -}}
  {{- /* range $secret := (include "sdhCommon.secrets.k8sSecretObjects" $theComponentSpec | fromYamlArray) */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    {{- toYaml $theComponentSpec.componentLabels | nindent 4 }}
type: Opaque
data: {{- $secret.data | toYaml | nindent 2 }}
---
  {{ end }}
{{ end }}
