{{- range $theComponentName, $theComponentSpec := include "pmp.components" . | fromYaml -}}
  {{- /* fail (printf "\n$theComponentName\n\n%s\n$theComponentSpec\n\n%s" $theComponentName (toYaml $theComponentSpec)) */ -}}
  {{- if ($theComponentSpec.ingress).enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $theComponentSpec.fullName }}
  labels:
    {{- toYaml $theComponentSpec.componentLabels | nindent 4 }}
  {{- with $theComponentSpec.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $theComponentSpec.ingress.tls }}
  tls:
    {{- range $theComponentSpec.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $theComponentSpec.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $theComponentSpec.fullName }}
                port:
                  number: {{ $theComponentSpec.service.port }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{ end }}
