# This GitLab CI file will do the following to ensure adherence to the SDLC for Helm Chart development at Smile Digital Health

variables:
  RELEASE_BRANCHES_PATTERN: '/^(main)$/'
  PRE_RELEASE_BRANCHES_PATTERN: '/^(next|pre-release|beta|alpha)$/'
  ALL_RELEASE_BRANCHES_PATTERN: '/^(main|next|pre-release|beta|alpha)$/'
  # Used to match against the auto-release commit. Used throughout, but there may be another way.
  RELEASE_COMMIT_MESSAGE: '/^chore\(auto-(pre)?release\)/'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"
      when: never
    - if: $CI_COMMIT_BRANCH
    # We can try tags again later on...
    # - if: $CI_COMMIT_BRANCH

stages:
- validate        # Run commit message checking, check for default tests

commit-check:
  stage: validate
  tags:
    - helm-ci
  image:
    name: commitizen/commitizen:2.37.0
  script:
    - export
    - cz check --rev-range HEAD

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  extends: .secret-analyzer
  stage: validate
  tags:
  - helm-ci
  rules:
    - if: $SECRET_DETECTION_DISABLED
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - /analyzer run
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"
