{{- /* Use the cdrNodes helper template that defines everything for a single CDR Node */ -}}
{{- range $theCdrNodeName, $theCdrNodeCtx := include "smilecdr.cdrNodes" . | fromYaml -}}
  {{- $theCdrNodeSpec := $theCdrNodeCtx.Values -}}
  {{- range $theCertificate := $theCdrNodeSpec.certificates -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $theCertificate.resourceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "smilecdr.labels" $ | nindent 4 | trim }}
spec:
  {{- $theCertificate.spec | toYaml | nindent 2 }}
---
  {{ end }}
{{ end }}
