{{- /* Use the nodes helper template that defines everything for a single CDR Node */ -}}
{{- range $theCdrNodeName, $theCdrNodeCtx := include "smilecdr.cdrNodes" . | fromYaml -}}
  {{- $theCdrNodeSpec := $theCdrNodeCtx.Values -}}
  {{- range $theCertificateName, $theCertificate := $theCdrNodeSpec.certificates -}}
    {{- /* Determine how to pass in the keystore secret*/ -}}


    {{- /* if and $theCertificate.enabled (($theCertificate.spec.keystores).pkcs12).create */ -}}
    {{- $keystorePasswordConfig := $theCertificate.keystorePasswordConfig -}}
    {{- if $keystorePasswordConfig.createSecret -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $keystorePasswordConfig.resourceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "smilecdr.labels" $ | nindent 4 | trim }}
type: Opaque
{{ $keystorePasswordConfig.secretData | toYaml }}
---
    {{- end }}
  {{- end }}
{{- end }}
