plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG-PRE.md"
  - - "@semantic-release/exec"
    - prepareCmd: "./scripts/semantic-release-prepare.sh ./src/ ${nextRelease.version}"
  - - "@semantic-release/gitlab"
    - assets:
      - "*.tgz"
      successComment: false
  - - "@semantic-release/git"
    - assets:
      - "src/"
      - "CHANGELOG-PRE.md"
      message: "chore(auto-prerelease): do pre-release ${nextRelease.version}\n\n${nextRelease.notes}"

branches:
  - name: "main"
  - name: "release-+([0-9]).x"
  - name: "next?(-+([0-9]).x)"
    prerelease: "beta"
  - name: "pre-release?(-+([0-9]).x)"
    prerelease: "pre"
