plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG-PRE.md"
  - - "@semantic-release/exec"
    - prepareCmd: "./scripts/semantic-release-prepare.sh ./src/ ${nextRelease.version}"
  - - "@semantic-release/gitlab"
    - assets:
      - "*.tgz"
  - - "@semantic-release/git"
    - assets:
      - "src/"
      - "CHANGELOG-PRE.md"
      message: "chore(auto-prerelease): do pre-release ${nextRelease.version}\n\n${nextRelease.notes}"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "main"
  - name: "alpha"
    prerelease: "alpha"
  - name: "beta"
    prerelease: "beta"
  - name: "pre-release"
    prerelease: "pre"
