{{- $lokiConfig := include "observability.lokideployment.config" . | fromYaml -}}
{{- if $lokiConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-loki-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
  annotations: {}
data:
  # Ref: https://github.com/grafana/loki/issues/10278
  local-config.yaml: |
    auth_enabled: false
    compactor:
      compaction_interval: 1m
    common:
      compactor_address: 'http://loki:3100'
      path_prefix: /loki
      replication_factor: 1
      storage:
        s3:
          bucketnames: sdh-smilelabs-file-staging20240410133315911100000001
          insecure: false
          region: us-east-1
          s3forcepathstyle: false
      # ring:
      #   kvstore:
      #     store: inmemory
    frontend:
      scheduler_address: ""
      tail_proxy_url: ""
    frontend_worker:
      scheduler_address: ""
    index_gateway:
      mode: simple
    limits_config:
      max_cache_freshness_per_query: 10m
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
      volume_enabled: true
    memberlist:
      join_members:
      - loki-memberlist
      # - "loki:7946"
    pattern_ingester:
      enabled: false
    query_range:
      align_queries_with_step: true
    ruler:
      storage:
        s3:
          bucketnames: sdh-smilelabs-file-staging20240410133315911100000001
          insecure: false
          region: us-east-1
          s3forcepathstyle: false
        type: s3
    # runtime_config:
    #   file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2024-01-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: filesystem
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
    storage_config:
      boltdb_shipper:
        index_gateway_client:
          server_address: ""
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        index_gateway_client:
          server_address: ""
    tracing:
      enabled: false
  
  local-config-custom.yaml: |
    auth_enabled: false
    common:
      # compactor_address: 'loki-read'
      # compactor_address: 'http://loki:3100'
      path_prefix: /loki
      replication_factor: 1
      storage:
        s3:
          bucketnames: {{ $lokiConfig.bucketNames.chunks }}
          # insecure: false
          region: us-east-1
          # s3: s3://us-east-1
    compactor:
      compaction_interval: 10m
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      retention_enabled: true
      shared_store: aws
      working_directory: /loki/compactor
    limits_config:
      enforce_metric_name: false
      ingestion_rate_strategy: local
      max_cache_freshness_per_query: 10m
      max_global_streams_per_user: 5000
      max_query_length: 2160h
      max_query_parallelism: 32
      max_streams_per_user: 10000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 2160h
      split_queries_by_interval: 15m
    # memberlist:
    #   join_members:
    #   - loki-memberlist
    query_range:
      align_queries_with_step: true
    ruler:
      storage:
        s3:
          bucketnames: {{ $lokiConfig.bucketNames.chunks }}
          insecure: false
          region: us-east-1
          s3: s3://us-east-1
          s3forcepathstyle: false
        type: s3
    # runtime_config:
    #   file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2023-03-20"
        index:
          period: 24h
          prefix: loki_sb_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      aws:
        s3: s3://us-east-1/{{ $lokiConfig.bucketNames.chunks }}
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/boltdb-cache
        # shared_store: s3
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
    table_manager:
      retention_deletes_enabled: false
      retention_period: 2160h

  local-config-old.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100

    common:
      path_prefix: /loki
      # compactor_address: 'http://release-name-loki:3100'
      # storage:
      #   # filesystem:
      #   #   chunks_directory: /loki/chunks
      #   #   rules_directory: /loki/rules      
      #   s3:
      #     s3: "s3://us-east-1"
      #     bucketnames: {{ $lokiConfig.bucketNames.chunks }}
      #     # bucketnames: bob
      #     region: us-east-1
      #     # Commented out as we are using IAM/IRSA
      #     # endpoint: foo.aws.com
      #     # secretAccessKey: supersecret
      #     # accessKeyId: secret
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /loki/wal

    compactor:
      working_directory: /loki/shipper-compactor
      compaction_interval: 1m
      shared_store: s3

    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: false
          embedded_cache:
            enabled: true
            max_size_mb: 500
            ttl: 24h

    chunk_store_config:
      max_look_back_period: 0s
      chunk_cache_config:
        embedded_cache:
          enabled: true
          max_size_mb: 500
          ttl: 24h

    storage_config:
      aws:
        s3: "s3://us-east-1/{{ $lokiConfig.bucketNames.chunks }}"
    #   aws:
    #     bucketnames: {{ $lokiConfig.bucketNames.chunks }}
    #     # bucketnames: bob
    #     region: us-east-1
    #   # tsdb_shipper:
    #   #   active_index_directory: /loki/tsdb-index2
    #   #   cache_location: /loki/tsdb-cache2
    #   #   shared_store: s3
    #   #   # index_gateway_client:
    #   #   #   server_address: ""
      
      boltdb_shipper:
        active_index_directory: /loki/boltdb-index
        cache_location: /loki/boltdb-cache
        cache_ttl: 168h
        shared_store: s3
        # store: s3
        # object_store: s3
        # shared_store: s3
      
      # hedging:
      #   at: 250ms
      #   max_per_second: 20
      #   up_to: 3
      

    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        # object_store: filesystem
        # store: aws
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

      # - from: 2024-04-01
      #   store: tsdb
      #   # object_store: filesystem
      #   object_store: s3
      #   schema: v13
      #   index:
      #     prefix: index_
      #     period: 24h
    analytics:
      reporting_enabled: false
{{- end -}}
