{{- $lokiConfig := include "observability.loki.config" . | fromYaml -}}
{{- if $lokiConfig.deployment.enabled -}}
{{- /* if (include "observability.lokideployment.enabled" . | fromYaml) */ -}}
apiVersion: v1
kind: Service
metadata:
  # name: {{ .Release.Name }}-loki
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
  annotations: {}
spec:
  type: "ClusterIP"
  ports:
    - name: loki
      port: {{ $lokiConfig.http_port }}
      targetPort: loki
      protocol: TCP
  selector:
    app: loki
    release: {{ .Release.Name }}
{{- end -}}
