{{- $lokiConfig := include "observability.loki.config" . | fromYaml -}}
{{- if $lokiConfig.deployment.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-loki-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
  annotations: {}
data:
  local-config.yaml: |
    auth_enabled: true
    common:
      compactor_address: {{ $lokiConfig.url }}
      path_prefix: /loki
      replication_factor: 1
      storage:
        s3:
          bucketnames: {{ $lokiConfig.bucketNames.chunks }}
          region: {{ $lokiConfig.bucketRegion }}
          insecure: false
          s3forcepathstyle: false
      ring:
        kvstore:
          store: inmemory
    compactor:
      compaction_interval: 1m
    ingester:
      chunk_idle_period: 10s
      chunk_retain_period: 20s
      max_chunk_age: 30s
      wal:
        flush_on_shutdown: true
    limits_config:
      allow_structured_metadata: true
      max_cache_freshness_per_query: 10m
      otlp_config:
        resource_attributes:
          attributes_config:
          - action: index_label
            attributes:
            - severity_text
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
      volume_enabled: true
    pattern_ingester:
      enabled: false
    query_range:
      align_queries_with_step: true
    ruler:
      storage:
        s3:
          bucketnames: {{ $lokiConfig.bucketNames.chunks }}
          region: {{ $lokiConfig.bucketRegion }}
          insecure: false
          s3forcepathstyle: false
        type: s3
    schema_config:
      configs:
      - from: "2024-01-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: {{ $lokiConfig.grpc_port }}
      http_listen_port: {{ $lokiConfig.http_port }}
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
    storage_config:
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        active_index_directory: /loki/tsdb_index
        cache_location: /loki/tsdb_index_cache
        index_gateway_client:
          server_address: ""
    tracing:
      enabled: false
  
{{- end -}}
