{{- $lokiConfig := include "observability.lokideployment.config" . | fromYaml -}}
{{- if $lokiConfig.enabled -}}
{{- /* if (include "observability.lokideployment.enabled" . | fromYaml) */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
  annotations: {}
spec:
  selector:
    matchLabels:
      app: loki
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: loki
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ $lokiConfig.serviceAccount.name }}
      containers:
      - name: loki
        image: grafana/loki:3.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: loki
          containerPort: 3100
          protocol: TCP
        - name: grpc
          containerPort: 9095
          protocol: TCP
        - name: http-memberlist
          containerPort: 7946
          protocol: TCP
        
        volumeMounts:
        - name: config-volume
          mountPath: /etc/loki/
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-loki-cm
{{- end -}}
