{{- $otelCollConfig := (include "observability.otelcoll" . | fromYaml) -}}
{{- if $otelCollConfig.crdEnabled -}}
{{- /* Define OpenTelemetryCollector resource for Smile CDR */ -}}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-scdr-otelcoll
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
  annotations: {}
spec:
  config: |
  {{- $otelCollConfig.yamlConfig | toYaml | nindent 4 }}
  # Using 'contrib' image as it has the required Loki exporter that is not in the 'core' distribution.
  # https://github.com/open-telemetry/opentelemetry-collector-releases/pkgs/container/opentelemetry-collector-releases%2Fopentelemetry-collector-contrib
  image: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.79.0"
  ingress:
    route: {}
  ports:
  - port: 9090
    name: otc-export
  mode: {{ .Values.observability.instrumentation.openTelemetry.otelCollector.mode }}
  replicas: 1
  resources: {}
  targetAllocator:
    prometheusCR: {}
    resources: {}
  upgradeStrategy: automatic
{{- end -}}
