{{- $otelAgentConfig := (include "observability.otelagent" . | fromYaml) -}}
{{- if $otelAgentConfig.useOperator -}}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Release.Name }}-scdr-instrumentation
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
spec:
    {{- $otelAgentConfig.spec | toYaml | nindent 4 }}

{{- end -}}
