{{- $otelCollConfig := (include "observability.otelcoll" . | fromYaml) -}}
{{- if $otelCollConfig.useOperator -}}
{{- /* Define OpenTelemetryCollector resource for Smile CDR */ -}}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-scdr-otelcoll
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
  annotations: {}
spec:
  config: |
  {{- $otelCollConfig.yamlConfig | toYaml | nindent 4 }}
  ingress:
    route: {}
  ports:
  - port: 9090
    name: otc-export
  mode: {{ .Values.observability.instrumentation.openTelemetry.otelCollector.mode }}
  replicas: 1
  resources: {}
  targetAllocator:
    prometheusCR: {}
    resources: {}
  upgradeStrategy: automatic
{{- end -}}
