{{- if (include "observability.otelagent" . | fromYaml).crdEnabled -}}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Release.Name }}-scdr-instrumentation
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
spec:
  exporter:
    endpoint: http://localhost:4317
  java:
    # image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.26.0
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
    env:
      # TODO: Needs review in case this is overriding these settings if they are set elsewhere
      # # Need to dynamically configure agent based on settings. none, otlp or zipkin
      # - name: OTEL_TRACES_EXPORTER
      #   value: none
      # # Need to dynamically configure agent based on settings. none, otlp or prometheus
      # - name: OTEL_METRICS_EXPORTER
      #   value: none
      # Need to dynamically configure agent based on settings. none or otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      # Just using these when using otlp logs exporter
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MARKER_ATTRIBUTE
        value: "true"
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_CODE_ATTRIBUTES
        value: "true"
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
        value: "true"
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_LOGGER_CONTEXT_ATTRIBUTES
        value: "true"
  propagators:
  - tracecontext
  - baggage
  - b3

  sampler:
    # Probability that a given sample will be retained.
    # https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampling
    # Lower probability if there is a lot of traffic. Increase or enable always on if doing one-off testing and you
    # need to see each span
    argument: "1"
    type: parentbased_traceidratio
{{- end -}}
