{{- if and .Values.database.crunchypgo.enabled .Values.database.crunchypgo.internal }}
{{- with .Values.database.crunchypgo.config }}
{{- if or .multiBackupRepos .s3 .gcs .azure }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-pgbackrest-secret
type: Opaque
data:
{{- if .multiBackupRepos }}
  {{- range $index, $repo := .multiBackupRepos }}
  {{- if $repo.s3 }}
  {{- $args := dict "s3" $repo.s3 "index" $index }}
  s3.conf: |-
        {{ include "postgres.s3" $args | b64enc }}
  {{- else if $repo.gcs }}
  {{- $args := dict "gcs" $repo.gcs "index" $index }}
  gcs.conf: |-
        {{ include "postgres.gcs" $args | b64enc }}
  gcs-key.json: |-
        {{ $repo.gcs.key | b64enc }}
  {{- else if $repo.azure }}
  {{- $args := dict "azure" $repo.azure "index" $index }}
  azure.conf: |-
        {{ include "postgres.azure" $args | b64enc }}
  {{- end }}
{{- end }}
{{- else if .s3 }}
  {{- $args := dict "s3" .s3 "index" 0 }}
  s3.conf: |-
        {{ include "postgres.s3" $args | b64enc }}
{{- else if .gcs }}
  {{- $args := dict "gcs" .gcs "index" 0 }}
  gcs.conf: |-
        {{ include "postgres.gcs" $args | b64enc }}
  gcs-key.json: |-
        {{ .gcs.key | b64enc }}
{{- else if .azure }}
  {{- $args := dict "azure" .azure "index" 0 }}
  azure.conf: |-
        {{ include "postgres.azure" $args | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}