{{- range $v := ( include "smilecdr.fileConfigMaps" . | fromYaml ).list -}}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if $.Values.autoDeploy }}
  name: {{ $.Release.Name }}-scdr-{{ $v.name | replace "." "-" }}-{{ $v.hash }}
  {{- else }}
  name: {{ $.Release.Name }}-scdr-{{ $v.name | replace "." "-" }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
data:
  {{ $v.name }}: |- {{ $v.data | nindent 4 }}
---
{{ end }}
