apiVersion: apps/v1
kind: Deployment
metadata:
  name: smilecdr-{{ .Values.labels.client }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "smilecdr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smilecdr.labels" . | nindent 8 }}
    spec:
      {{- with (include "dockerconfigjson.secretName" .) }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "smilecdr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "smilecdr.dbSecretName" . }}
                  key: host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "smilecdr.dbSecretName" . }}
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "smilecdr.dbSecretName" . }}
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "smilecdr.dbSecretName" . }}
                  key: password
          ports:
            {{- range $k, $v := include "smilecdr.services" . | fromYaml }}
            - name: {{ $v.svcName }}
              containerPort: {{ $v.port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: smilecdr-config-{{ .Values.labels.client }}
              mountPath: /home/smile/smilecdr/classes/cdr-config-Master.properties
              subPath: cdr-config-Master.properties
            - name: smilecdr-tls-cert-{{ .Values.labels.client }}
              mountPath: "/etc/ssl/smile"
              readOnly: true
            {{- if .Values.mappedFiles -}}
              {{- include "smilecdr.fileVolumeMounts" .  | trim | nindent 12 }}
            {{- end }}
      volumes:
        - name: smilecdr-config-{{ .Values.labels.client }}
          configMap:
            name: smilecdr-config-{{ .Values.labels.client }}
        - name: smilecdr-tls-cert-{{ .Values.labels.client }}
          secret:
            secretName: cdr-dev-tls-cert
        {{- if .Values.mappedFiles -}}
          {{- include "smilecdr.fileVolumes" .  | trim | nindent 8 }}
        {{- end }}
      restartPolicy: Always
