{{- if eq .Values.image.credentials.type "values" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dockerconfigjson.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  dockerconfigjson: {{ include "dockerconfigjson.encoded" . }}
{{- end -}}
