{
 "title": "Summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(http_server_duration_milliseconds_bucket{http_status_code=\"200\"}[2m])) by (le))",
     "legendFormat": "p100"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{http_status_code=\"200\"}[2m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{http_status_code=\"200\"}[2m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_milliseconds_bucket{http_status_code=\"200\"}[2m])) by (le))",
     "legendFormat": "p80"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(http_server_duration_milliseconds_bucket{http_status_code=\"200\"}[2m])) by (le))",
     "legendFormat": "p65"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_duration_milliseconds_bucket{http_status_code=\"200\"}[2m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Healthcheck Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(http_server_duration_milliseconds_bucket{http_route=\"/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m])) by (le))",
     "legendFormat": "p100"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{http_route=\"/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{http_route=\"/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_milliseconds_bucket{http_route=\"/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m])) by (le))",
     "legendFormat": "p80"
    },
    {
     "expr": "histogram_quantile(0.65, sum(rate(http_server_duration_milliseconds_bucket{http_route=\"/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m])) by (le))",
     "legendFormat": "p65"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"250\",http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m]))\n+\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"750\",http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m]))\n) / 2 / \nsum(rate(http_server_duration_milliseconds_count{http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m]))",
     "legendFormat": "5 mins"
    },
    {
     "expr": "(\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"250\",http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[12h]))\n+\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"750\",http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[12h]))\n) / 2 / \nsum(rate(http_server_duration_milliseconds_count{http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[12h]))",
     "legendFormat": "12h"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"250\",http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m]))\n+\n    sum(rate(http_server_duration_milliseconds_bucket{le=\"750\",http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m]))\n) / 2 / \nsum(rate(http_server_duration_milliseconds_count{http_route=~\"/fhir_request/|/fhir_request/endpoint-health\",http_status_code=\"200\"}[5m])) - 0.01",
     "legendFormat": "Score"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{}[2m])) / sum(rate(http_server_duration_milliseconds_count{}[2m]))",
     "legendFormat": "2 mins"
    }
   ]
  },
  {
   "title": "Request Duration (All)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{}[2m])) / sum(rate(http_server_duration_milliseconds_count{}[2m]))",
     "legendFormat": "2 mins"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{}[2m])) / sum(rate(http_server_duration_milliseconds_count{}[2m]))",
     "legendFormat": "2 mins"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{}[5m])) / sum(rate(http_server_duration_milliseconds_count{}[5m]))",
     "legendFormat": "5 mins"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{}[30m])) / sum(rate(http_server_duration_milliseconds_count{}[30m]))",
     "legendFormat": "30 mins"
    }
   ]
  },
  {
   "title": "Request Duration (FHIR)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{http_route=\"/fhir_request/\"}[2m])) / sum(rate(http_server_duration_milliseconds_count{http_route=\"/fhir_request/\"}[2m]))",
     "legendFormat": "2 mins"
    }
   ]
  },
  { "title": "HTTP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Overall Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(http_responses_total{}[$__rate_interval]))",
     "legendFormat": "Rate"
    },
    {
     "editormode": "builder",
     "expr": "sum (http_server_active_requests{})",
     "legendFormat": "Active Requests "
    }
   ]
  },
  {
   "title": "Total Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(http_responses_total{http_status_code!=\"4xx|5xx\"}[$__rate_interval]))",
     "legendFormat": "OK"
    },
    {
     "editormode": "builder",
     "expr": "sum (rate(http_responses_total{http_status_code=~\"4xx|5xx\"}[$__rate_interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate(label_replace(label_replace({__name__=~\".*_http_responses_[2,3]xx_total\"},\"module\",\"$1\",\"__name__\", \"(.*)_http_responses_[2,3]xx_total\"),\"http_status_code\",\"$1\",\"__name__\", \".*_http_responses_([2,3]xx)_total\")[$__rate_interval:]))",
     "legendFormat": "Label Replace"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{ http_status_code=~\"[2,3]..\"}[2m]))",
     "legendFormat": "OTC"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum(rate(http_server_request_size_bytes_sum[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Searches",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(persistence_fhir_searches_active{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FHIR Transactions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(overall_transaction_metric_count{endpoint_type=~\"admin|fhir\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Transactions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(overall_transaction_metric_count{endpoint_type!=\"admin|fhir\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(http_responses_total{http_status_code=~\"4xx|5xx\"}[$__rate_interval])) / sum (rate(http_responses_total{}[$__rate_interval])) / sum (rate(http_responses_total{}[$__rate_interval])) / sum (rate(http_responses_total{}[$__rate_interval]))",
     "legendFormat": " "
    },
    {
     "expr": "sum (rate(http_responses_total{http_status_code=~\"4xx|5xx\"}[$__rate_interval]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_size_bytes_sum[5m]))",
     "legendFormat": "Bytes/sec"
    }
   ]
  },
  {
   "title": "Active Searches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 25 },
   "targets": [
    {
     "expr": "sum(persistence_fhir_searches_active{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions / Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(overall_transaction_metric_count{endpoint_type=~\"admin|fhir\"}[$__rate_interval]))",
     "legendFormat": "Transactions / Sec"
    }
   ]
  },
  {
   "title": "Transactions / Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(overall_transaction_metric_count{endpoint_type!=\"admin|fhir\"}[$__rate_interval]))",
     "legendFormat": "Transactions / Sec"
    }
   ]
  },
  { "title": "FHIR Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 33 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum(jvm_threads_state) by(state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum (rate(http_responses_total{}[$__rate_interval]))",
     "legendFormat": "Rate"
    },
    {
     "editormode": "builder",
     "expr": "sum (http_server_active_requests{})",
     "legendFormat": "Active Requests "
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "editormode": "builder",
     "expr": "sum by(cdr_module_name)(rate(http_responses_total{cdr_module_name=~\"$cdrModule\",http_code=\"5xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}