apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  # name: {{ .Chart.Name }}
spec:
  amiFamily: AL2
  role: {{ .Values.karpenterIamRole }}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: {{ .Values.clusterName }}
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: {{ .Values.clusterName }}
  tags:
    karpenter.sh/discovery: {{ .Values.clusterName }}