{{- range $v := ( include "keycloak.fileConfigMaps" . | fromYamlArray ) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if $.Values.autoDeploy }}
  name: {{ $.Release.Name }}-keycloak-{{ $v.name | replace "." "-" | replace "_" "-" | lower }}-{{ $v.hash }}
  {{- else }}
  name: {{ $.Release.Name }}-keycloak-{{ $v.name | replace "." "-" | replace "_" "-" | lower }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
  {{- if ($.Values.argocd).enabled }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  {{- end }}
data:
  {{ $v.name }}: |- {{ $v.data | nindent 4 }}
---
{{ end }}
