{{- range $secret := (include "sdhCommon.secrets.k8sSecretObjects" . | fromYamlArray) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
type: Opaque
data: {{- $secret.data | toYaml | nindent 2 }}
---
{{ end }}
