{{- if eq .Values.messageBroker.adminPod.enabled true -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-kafka-admin
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kafka.admin.labels" $ | nindent 4 }}
  {{- if ($.Values.argocd).enabled }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  {{- end }}
data:
  client.properties.template: |-
    {{- include "kafka.admin.consumer.properties.text" . | nindent 4 }}
  entrypoint.sh: |-
    #!/bin/sh
    mkdir -p /opt/kafka/custom-config/
    # This creates a config file for use by Kafka CLI commands
    /usr/bin/envsubst < /tmp/templates/client.properties.template > /opt/kafka/custom-config/client.properties
    # Modify the kafka-run-class to include the above config file and the bootstrap address from the environment.
    # It seems there is no built-in way to auto configure these details in Kafka...
    /bin/sed -i -E 's/(\$KAFKA_OPTS \"\$@\")$/\1 --command-config \/opt\/kafka\/custom-config\/client.properties --bootstrap-server \${KAFKA_BOOTSTRAP_ADDRESS}/g' /opt/kafka/bin/kafka-run-class.sh
    sleep 360000
{{- end -}}
