{{- range $theNodeName, $theNodeCtx := include "smilecdr.nodes" . | fromYaml -}}
  {{- $theNodeSpec := $theNodeCtx.Values -}}
  {{- if ($theNodeSpec.kafka).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $theNodeSpec.kafka.propertiesResourceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "smilecdr.labels" $ | nindent 4 }}
  {{- if ($.Values.argocd).enabled }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  {{- end }}
data:
  consumer.properties: |-
    {{- printf $theNodeSpec.kafka.consumerPropertiesData | nindent 4 }}
  producer.properties: |-
    {{- printf $theNodeSpec.kafka.producerPropertiesData | nindent 4 }}
---
  {{ end }}
{{ end }}
